(() => {
  const params = new URLSearchParams(location.search); const topic = (window.FINDORY_TOPICS || []).find((entry) => entry.id === params.get('thema')); const guides = window.FINDORY_GUIDES || [];
  const headline = document.querySelector('#category-view'); const list = document.querySelector('#subtopic-list'); const contentArea = document.querySelector('#content-area');
  if (!topic) { headline.innerHTML = '<h1>Themenwelt nicht gefunden</h1><p>Bitte wähle eine Themenwelt auf der Startseite.</p>'; return; }
  const selected = topic.items.find((item) => item.id === params.get('unterthema')); const selectedArea = selected?.subtopics.find((area) => area.id === params.get('bereich'));
  const link = (item, area) => `category.html?thema=${encodeURIComponent(topic.id)}&unterthema=${encodeURIComponent(item.id)}${area ? `&bereich=${encodeURIComponent(area.id)}` : ''}`;
  const areaCard = (item, area) => `<a class="detail-link" href="${link(item, area)}"><p class="detail-parent">${item.title}</p><h2>${area.title}</h2><p>${area.intro}</p><span>Bereich öffnen →</span></a>`;
  document.title = `Findory – ${selectedArea?.title || selected?.title || topic.title}`;
  if (!selected) { headline.innerHTML = `<p class="eyebrow">${topic.title}</p><h1>Alle Lösungsbereiche</h1><p>${topic.intro} Wähle ein konkretes Anliegen, damit du gezielt zu passenden Ratgebern und späteren Produktempfehlungen gelangst.</p>`; contentArea.innerHTML = '<div class="section-intro"><h2>Womit möchtest du anfangen?</h2><p>Jeder Bereich führt zu einer eigenen, später erweiterbaren Themenstruktur.</p></div>'; list.innerHTML = topic.items.flatMap((item) => item.subtopics.map((area) => areaCard(item, area))).join(''); return; }
  headline.innerHTML = `<p class="eyebrow">${topic.title}</p><h1>${selectedArea?.title || selected.title}</h1><p>${selectedArea?.intro || selected.intro} Hier entstehen Schritt für Schritt hilfreiche Ratgeber, Vergleiche und erst nach Prüfung konkrete Produktempfehlungen.</p>`;
  const related = guides.filter((guide) => guide.topicId === topic.id && guide.itemId === selected.id);
  contentArea.innerHTML = related.length ? `<section class="guide-callout"><div><p>Ratgeber & Vergleiche</p><h2>Produkte vergleichen. Passender entscheiden.</h2><span>Wir zeigen Kriterien, Stärken und Grenzen verschiedener Produkttypen. Jedes aufgenommene Vergleichsprodukt kann später direkt zu deinem Affiliate-Link führen.</span></div><a href="ratgeber-beitrag.html?guide=${encodeURIComponent(related[0].id)}">Vergleich lesen →</a></section>` : '<div class="section-intro"><h2>Dieser Bereich wird vorbereitet.</h2><p>Die Struktur steht. Ein fundierter Ratgeber folgt, sobald das Thema recherchiert ist.</p></div>';
  list.innerHTML = selected.subtopics.map((area) => areaCard(selected, area)).join('');
})();
